### ISSUE TITLE
Requiring Hash::Util::hash_traversal_mask makes tests fail on perls < 5.18

### ISSUE THREAD

**Issue by tehmoth** [zoffixznet/Number-RGB#2]
$ make test
cp lib/Number/RGB.pm blib/lib/Number/RGB.pm
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef _Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/_.t
t/00-compile.t ........ ok  
t/01_functionality.t .. "hash_traversal_mask" is not exported by the Hash::Util module
Can't continue after import errors at t/01_functionality.t line 7.
BEGIN failed--compilation aborted at t/01_functionality.t line 7.
t/01_functionality.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 

Module installs on 5.16 with --notest

**Comment by zoffixznet** [comment]
Thanks a lot! Some vestigial code left over from trying to write a test for #1 :disappointed:
